### ISSUE TITLE
Fails to build with ESPHome 2025.8.0

### ISSUE THREAD

**Issue by rvdbijl** [dannerph/esphome_vitoconnect#17]
See output below: 

Compiling .pioenvs/viessmann-boiler-sensors/src/esphome/core/scheduler.cpp.o
In file included from src/esphome/components/vitoconnect/vitoconnect_optolink.h:80,
                 from src/esphome/components/vitoconnect/vitoconnect_optolink.cpp:26:
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h: In copy constructor 'esphome::vitoconnect::SimpleQueue<T>::SimpleQueue(const esphome::vitoconnect::SimpleQueue<T>&)':
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h:67:11: error: assignment of read-only member 'esphome::vitoconnect::SimpleQueue<T>::_size'
   67 |     _size = obj._size;
      |     ~~~~~~^~~~~~~~~~~
In file included from src/esphome/components/vitoconnect/vitoconnect_optolink.h:80,
                 from src/esphome/components/vitoconnect/vitoconnect_optolinkKW.h:36,
                 from src/esphome/components/vitoconnect/vitoconnect_optolinkKW.cpp:26:
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h: In copy constructor 'esphome::vitoconnect::SimpleQueue<T>::SimpleQueue(const esphome::vitoconnect::SimpleQueue<T>&)':
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h:67:11: error: assignment of read-only member 'esphome::vitoconnect::SimpleQueue<T>::_size'
   67 |     _size = obj._size;
      |     ~~~~~~^~~~~~~~~~~
*** [.pioenvs/viessmann-boiler-sensors/src/esphome/components/vitoconnect/vitoconnect_optolink.cpp.o] Error 1
*** [.pioenvs/viessmann-boiler-sensors/src/esphome/components/vitoconnect/vitoconnect_optolinkKW.cpp.o] Error 1
In file included from src/esphome/components/vitoconnect/vitoconnect_optolink.h:80,
                 from src/esphome/components/vitoconnect/vitoconnect_optolinkP300.h:36,
                 from src/esphome/components/vitoconnect/vitoconnect_optolinkP300.cpp:26:
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h: In copy constructor 'esphome::vitoconnect::SimpleQueue<T>::SimpleQueue(const esphome::vitoconnect::SimpleQueue<T>&)':
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h:67:11: error: assignment of read-only member 'esphome::vitoconnect::SimpleQueue<T>::_size'
   67 |     _size = obj._size;
      |     ~~~~~~^~~~~~~~~~~
*** [.pioenvs/viessmann-boiler-sensors/src/esphome/components/vitoconnect/vitoconnect_optolinkP300.cpp.o] Error 1
In file included from src/esphome/components/vitoconnect/vitoconnect_optolink.h:80,
                 from src/esphome/components/vitoconnect/vitoconnect.h:27,
                 from src/esphome/components/vitoconnect/vitoconnect.cpp:20:
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h: In copy constructor 'esphome::vitoconnect::SimpleQueue<T>::SimpleQueue(const esphome::vitoconnect::SimpleQueue<T>&)':
src/esphome/components/vitoconnect/vitoconnect_simpleQueue.h:67:11: error: assignment of read-only member 'esphome::vitoconnect::SimpleQueue<T>::_size'
   67 |     _size = obj._size;
      |     ~~~~~~^~~~~~~~~~~
*** [.pioenvs/viessmann-boiler-sensors/src/esphome/components/vitoconnect/vitoconnect.cpp.o] Error 1

**Comment by kaeon** [comment]
i have the same!

the const should be gone!
